// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: jwtrpcdeclare.proto

package jwtrpcdeclare

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncryptionAlgorithm int32

const (
	EncryptionAlgorithm_UNKNOWN EncryptionAlgorithm = 0
	EncryptionAlgorithm_RS256   EncryptionAlgorithm = 1
	EncryptionAlgorithm_RS384   EncryptionAlgorithm = 2
	EncryptionAlgorithm_RS512   EncryptionAlgorithm = 3
	EncryptionAlgorithm_ES256   EncryptionAlgorithm = 4
	EncryptionAlgorithm_ES384   EncryptionAlgorithm = 5
	EncryptionAlgorithm_ES512   EncryptionAlgorithm = 6
	EncryptionAlgorithm_HS256   EncryptionAlgorithm = 7
	EncryptionAlgorithm_HS384   EncryptionAlgorithm = 8
	EncryptionAlgorithm_HS512   EncryptionAlgorithm = 9
)

// Enum value maps for EncryptionAlgorithm.
var (
	EncryptionAlgorithm_name = map[int32]string{
		0: "UNKNOWN",
		1: "RS256",
		2: "RS384",
		3: "RS512",
		4: "ES256",
		5: "ES384",
		6: "ES512",
		7: "HS256",
		8: "HS384",
		9: "HS512",
	}
	EncryptionAlgorithm_value = map[string]int32{
		"UNKNOWN": 0,
		"RS256":   1,
		"RS384":   2,
		"RS512":   3,
		"ES256":   4,
		"ES384":   5,
		"ES512":   6,
		"HS256":   7,
		"HS384":   8,
		"HS512":   9,
	}
)

func (x EncryptionAlgorithm) Enum() *EncryptionAlgorithm {
	p := new(EncryptionAlgorithm)
	*p = x
	return p
}

func (x EncryptionAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EncryptionAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_jwtrpcdeclare_proto_enumTypes[0].Descriptor()
}

func (EncryptionAlgorithm) Type() protoreflect.EnumType {
	return &file_jwtrpcdeclare_proto_enumTypes[0]
}

func (x EncryptionAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EncryptionAlgorithm.Descriptor instead.
func (EncryptionAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_jwtrpcdeclare_proto_rawDescGZIP(), []int{0}
}

type MetaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MetaRequest) Reset() {
	*x = MetaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jwtrpcdeclare_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaRequest) ProtoMessage() {}

func (x *MetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jwtrpcdeclare_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaRequest.ProtoReflect.Descriptor instead.
func (*MetaRequest) Descriptor() ([]byte, []int) {
	return file_jwtrpcdeclare_proto_rawDescGZIP(), []int{0}
}

type MetaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Algo                     EncryptionAlgorithm `protobuf:"varint,1,opt,name=algo,proto3,enum=jwtrpcdeclare.EncryptionAlgorithm" json:"algo,omitempty"`
	Iss                      string              `protobuf:"bytes,2,opt,name=iss,proto3" json:"iss,omitempty"`
	DefaultTTL               int64               `protobuf:"varint,3,opt,name=defaultTTL,proto3" json:"defaultTTL,omitempty"`
	DefaultEffectiveInterval int64               `protobuf:"varint,4,opt,name=defaultEffectiveInterval,proto3" json:"defaultEffectiveInterval,omitempty"`
	JtiGen                   string              `protobuf:"bytes,5,opt,name=jtiGen,proto3" json:"jtiGen,omitempty"`
}

func (x *MetaResponse) Reset() {
	*x = MetaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jwtrpcdeclare_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaResponse) ProtoMessage() {}

func (x *MetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jwtrpcdeclare_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaResponse.ProtoReflect.Descriptor instead.
func (*MetaResponse) Descriptor() ([]byte, []int) {
	return file_jwtrpcdeclare_proto_rawDescGZIP(), []int{1}
}

func (x *MetaResponse) GetAlgo() EncryptionAlgorithm {
	if x != nil {
		return x.Algo
	}
	return EncryptionAlgorithm_UNKNOWN
}

func (x *MetaResponse) GetIss() string {
	if x != nil {
		return x.Iss
	}
	return ""
}

func (x *MetaResponse) GetDefaultTTL() int64 {
	if x != nil {
		return x.DefaultTTL
	}
	return 0
}

func (x *MetaResponse) GetDefaultEffectiveInterval() int64 {
	if x != nil {
		return x.DefaultEffectiveInterval
	}
	return 0
}

func (x *MetaResponse) GetJtiGen() string {
	if x != nil {
		return x.JtiGen
	}
	return ""
}

type SignRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Sub     string   `protobuf:"bytes,2,opt,name=sub,proto3" json:"sub,omitempty"`
	Exp     int64    `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`
	Nbf     int64    `protobuf:"varint,4,opt,name=nbf,proto3" json:"nbf,omitempty"`
	Aud     []string `protobuf:"bytes,5,rep,name=aud,proto3" json:"aud,omitempty"`
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jwtrpcdeclare_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jwtrpcdeclare_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_jwtrpcdeclare_proto_rawDescGZIP(), []int{2}
}

func (x *SignRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SignRequest) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *SignRequest) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *SignRequest) GetNbf() int64 {
	if x != nil {
		return x.Nbf
	}
	return 0
}

func (x *SignRequest) GetAud() []string {
	if x != nil {
		return x.Aud
	}
	return nil
}

type VerifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jwtrpcdeclare_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jwtrpcdeclare_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_jwtrpcdeclare_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SignResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jwtrpcdeclare_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jwtrpcdeclare_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_jwtrpcdeclare_proto_rawDescGZIP(), []int{4}
}

func (x *SignResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jwtrpcdeclare_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jwtrpcdeclare_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_jwtrpcdeclare_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_jwtrpcdeclare_proto protoreflect.FileDescriptor

var file_jwtrpcdeclare_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6a, 0x77, 0x74, 0x72, 0x70, 0x63, 0x64, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6a, 0x77, 0x74, 0x72, 0x70, 0x63, 0x64, 0x65, 0x63,
	0x6c, 0x61, 0x72, 0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0xcc, 0x01, 0x0a, 0x0c, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x04, 0x61, 0x6c, 0x67, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x22, 0x2e, 0x6a, 0x77, 0x74, 0x72, 0x70, 0x63, 0x64, 0x65, 0x63, 0x6c, 0x61,
	0x72, 0x65, 0x2e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6c, 0x67,
	0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x52, 0x04, 0x61, 0x6c, 0x67, 0x6f, 0x12, 0x10, 0x0a, 0x03,
	0x69, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x73, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x54, 0x54, 0x4c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x54, 0x54, 0x4c, 0x12, 0x3a,
	0x0a, 0x18, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x18, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x6a, 0x74,
	0x69, 0x47, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6a, 0x74, 0x69, 0x47,
	0x65, 0x6e, 0x22, 0x6f, 0x0a, 0x0b, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x75, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x75, 0x62, 0x12, 0x10, 0x0a,
	0x03, 0x65, 0x78, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x78, 0x70, 0x12,
	0x10, 0x0a, 0x03, 0x6e, 0x62, 0x66, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x62,
	0x66, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x75, 0x64, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03,
	0x61, 0x75, 0x64, 0x22, 0x25, 0x0a, 0x0d, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x24, 0x0a, 0x0c, 0x53, 0x69,
	0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x2a, 0x0a, 0x0e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2a, 0x85, 0x01, 0x0a,
	0x13, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6c, 0x67, 0x6f, 0x72,
	0x69, 0x74, 0x68, 0x6d, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x53, 0x32, 0x35, 0x36, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05,
	0x52, 0x53, 0x33, 0x38, 0x34, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x53, 0x35, 0x31, 0x32,
	0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x53, 0x32, 0x35, 0x36, 0x10, 0x04, 0x12, 0x09, 0x0a,
	0x05, 0x45, 0x53, 0x33, 0x38, 0x34, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x53, 0x35, 0x31,
	0x32, 0x10, 0x06, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x53, 0x32, 0x35, 0x36, 0x10, 0x07, 0x12, 0x09,
	0x0a, 0x05, 0x48, 0x53, 0x33, 0x38, 0x34, 0x10, 0x08, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x53, 0x35,
	0x31, 0x32, 0x10, 0x09, 0x32, 0xdb, 0x01, 0x0a, 0x0a, 0x4a, 0x77, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x1a, 0x2e, 0x6a, 0x77,
	0x74, 0x72, 0x70, 0x63, 0x64, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6a, 0x77, 0x74, 0x72, 0x70, 0x63,
	0x64, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x12, 0x1a,
	0x2e, 0x6a, 0x77, 0x74, 0x72, 0x70, 0x63, 0x64, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x65, 0x2e, 0x53,
	0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6a, 0x77, 0x74,
	0x72, 0x70, 0x63, 0x64, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x65, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x06, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x12, 0x1c, 0x2e, 0x6a, 0x77, 0x74, 0x72, 0x70, 0x63, 0x64, 0x65, 0x63, 0x6c,
	0x61, 0x72, 0x65, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x6a, 0x77, 0x74, 0x72, 0x70, 0x63, 0x64, 0x65, 0x63, 0x6c, 0x61, 0x72,
	0x65, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x6a, 0x77, 0x74, 0x72, 0x70, 0x63, 0x64, 0x65,
	0x63, 0x6c, 0x61, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jwtrpcdeclare_proto_rawDescOnce sync.Once
	file_jwtrpcdeclare_proto_rawDescData = file_jwtrpcdeclare_proto_rawDesc
)

func file_jwtrpcdeclare_proto_rawDescGZIP() []byte {
	file_jwtrpcdeclare_proto_rawDescOnce.Do(func() {
		file_jwtrpcdeclare_proto_rawDescData = protoimpl.X.CompressGZIP(file_jwtrpcdeclare_proto_rawDescData)
	})
	return file_jwtrpcdeclare_proto_rawDescData
}

var file_jwtrpcdeclare_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jwtrpcdeclare_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_jwtrpcdeclare_proto_goTypes = []interface{}{
	(EncryptionAlgorithm)(0), // 0: jwtrpcdeclare.EncryptionAlgorithm
	(*MetaRequest)(nil),      // 1: jwtrpcdeclare.MetaRequest
	(*MetaResponse)(nil),     // 2: jwtrpcdeclare.MetaResponse
	(*SignRequest)(nil),      // 3: jwtrpcdeclare.SignRequest
	(*VerifyRequest)(nil),    // 4: jwtrpcdeclare.VerifyRequest
	(*SignResponse)(nil),     // 5: jwtrpcdeclare.SignResponse
	(*VerifyResponse)(nil),   // 6: jwtrpcdeclare.VerifyResponse
}
var file_jwtrpcdeclare_proto_depIdxs = []int32{
	0, // 0: jwtrpcdeclare.MetaResponse.algo:type_name -> jwtrpcdeclare.EncryptionAlgorithm
	1, // 1: jwtrpcdeclare.JwtService.Meta:input_type -> jwtrpcdeclare.MetaRequest
	3, // 2: jwtrpcdeclare.JwtService.Sign:input_type -> jwtrpcdeclare.SignRequest
	4, // 3: jwtrpcdeclare.JwtService.Verify:input_type -> jwtrpcdeclare.VerifyRequest
	2, // 4: jwtrpcdeclare.JwtService.Meta:output_type -> jwtrpcdeclare.MetaResponse
	5, // 5: jwtrpcdeclare.JwtService.Sign:output_type -> jwtrpcdeclare.SignResponse
	6, // 6: jwtrpcdeclare.JwtService.Verify:output_type -> jwtrpcdeclare.VerifyResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_jwtrpcdeclare_proto_init() }
func file_jwtrpcdeclare_proto_init() {
	if File_jwtrpcdeclare_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jwtrpcdeclare_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jwtrpcdeclare_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jwtrpcdeclare_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jwtrpcdeclare_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jwtrpcdeclare_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jwtrpcdeclare_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jwtrpcdeclare_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jwtrpcdeclare_proto_goTypes,
		DependencyIndexes: file_jwtrpcdeclare_proto_depIdxs,
		EnumInfos:         file_jwtrpcdeclare_proto_enumTypes,
		MessageInfos:      file_jwtrpcdeclare_proto_msgTypes,
	}.Build()
	File_jwtrpcdeclare_proto = out.File
	file_jwtrpcdeclare_proto_rawDesc = nil
	file_jwtrpcdeclare_proto_goTypes = nil
	file_jwtrpcdeclare_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// JwtServiceClient is the client API for JwtService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JwtServiceClient interface {
	//查看jwt服务元信息的算法
	Meta(ctx context.Context, in *MetaRequest, opts ...grpc.CallOption) (*MetaResponse, error)
	// Sign 为JSON字符串签名
	Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error)
	// Verify 将token解析到的负载转码为JSON字符串返回
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
}

type jwtServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJwtServiceClient(cc grpc.ClientConnInterface) JwtServiceClient {
	return &jwtServiceClient{cc}
}

func (c *jwtServiceClient) Meta(ctx context.Context, in *MetaRequest, opts ...grpc.CallOption) (*MetaResponse, error) {
	out := new(MetaResponse)
	err := c.cc.Invoke(ctx, "/jwtrpcdeclare.JwtService/Meta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jwtServiceClient) Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	out := new(SignResponse)
	err := c.cc.Invoke(ctx, "/jwtrpcdeclare.JwtService/Sign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jwtServiceClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, "/jwtrpcdeclare.JwtService/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JwtServiceServer is the server API for JwtService service.
type JwtServiceServer interface {
	//查看jwt服务元信息的算法
	Meta(context.Context, *MetaRequest) (*MetaResponse, error)
	// Sign 为JSON字符串签名
	Sign(context.Context, *SignRequest) (*SignResponse, error)
	// Verify 将token解析到的负载转码为JSON字符串返回
	Verify(context.Context, *VerifyRequest) (*VerifyResponse, error)
}

// UnimplementedJwtServiceServer can be embedded to have forward compatible implementations.
type UnimplementedJwtServiceServer struct {
}

func (*UnimplementedJwtServiceServer) Meta(context.Context, *MetaRequest) (*MetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Meta not implemented")
}
func (*UnimplementedJwtServiceServer) Sign(context.Context, *SignRequest) (*SignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sign not implemented")
}
func (*UnimplementedJwtServiceServer) Verify(context.Context, *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}

func RegisterJwtServiceServer(s *grpc.Server, srv JwtServiceServer) {
	s.RegisterService(&_JwtService_serviceDesc, srv)
}

func _JwtService_Meta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JwtServiceServer).Meta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jwtrpcdeclare.JwtService/Meta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JwtServiceServer).Meta(ctx, req.(*MetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JwtService_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JwtServiceServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jwtrpcdeclare.JwtService/Sign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JwtServiceServer).Sign(ctx, req.(*SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JwtService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JwtServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jwtrpcdeclare.JwtService/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JwtServiceServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JwtService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "jwtrpcdeclare.JwtService",
	HandlerType: (*JwtServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Meta",
			Handler:    _JwtService_Meta_Handler,
		},
		{
			MethodName: "Sign",
			Handler:    _JwtService_Sign_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _JwtService_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jwtrpcdeclare.proto",
}
