// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.1
// source: pbschema/jwt.proto

package jwt_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncryptionAlgorithm int32

const (
	EncryptionAlgorithm_UNKNOWN EncryptionAlgorithm = 0
	EncryptionAlgorithm_RS256   EncryptionAlgorithm = 1
	EncryptionAlgorithm_RS384   EncryptionAlgorithm = 2
	EncryptionAlgorithm_RS512   EncryptionAlgorithm = 3
	EncryptionAlgorithm_ES256   EncryptionAlgorithm = 4
	EncryptionAlgorithm_ES384   EncryptionAlgorithm = 5
	EncryptionAlgorithm_ES512   EncryptionAlgorithm = 6
	EncryptionAlgorithm_HS256   EncryptionAlgorithm = 7
	EncryptionAlgorithm_HS384   EncryptionAlgorithm = 8
	EncryptionAlgorithm_HS512   EncryptionAlgorithm = 9
)

// Enum value maps for EncryptionAlgorithm.
var (
	EncryptionAlgorithm_name = map[int32]string{
		0: "UNKNOWN",
		1: "RS256",
		2: "RS384",
		3: "RS512",
		4: "ES256",
		5: "ES384",
		6: "ES512",
		7: "HS256",
		8: "HS384",
		9: "HS512",
	}
	EncryptionAlgorithm_value = map[string]int32{
		"UNKNOWN": 0,
		"RS256":   1,
		"RS384":   2,
		"RS512":   3,
		"ES256":   4,
		"ES384":   5,
		"ES512":   6,
		"HS256":   7,
		"HS384":   8,
		"HS512":   9,
	}
)

func (x EncryptionAlgorithm) Enum() *EncryptionAlgorithm {
	p := new(EncryptionAlgorithm)
	*p = x
	return p
}

func (x EncryptionAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EncryptionAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_pbschema_jwt_proto_enumTypes[0].Descriptor()
}

func (EncryptionAlgorithm) Type() protoreflect.EnumType {
	return &file_pbschema_jwt_proto_enumTypes[0]
}

func (x EncryptionAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EncryptionAlgorithm.Descriptor instead.
func (EncryptionAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_pbschema_jwt_proto_rawDescGZIP(), []int{0}
}

type ResponseStatus_Stat int32

const (
	ResponseStatus_SUCCEED ResponseStatus_Stat = 0
	ResponseStatus_FAILED  ResponseStatus_Stat = 1
)

// Enum value maps for ResponseStatus_Stat.
var (
	ResponseStatus_Stat_name = map[int32]string{
		0: "SUCCEED",
		1: "FAILED",
	}
	ResponseStatus_Stat_value = map[string]int32{
		"SUCCEED": 0,
		"FAILED":  1,
	}
)

func (x ResponseStatus_Stat) Enum() *ResponseStatus_Stat {
	p := new(ResponseStatus_Stat)
	*p = x
	return p
}

func (x ResponseStatus_Stat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseStatus_Stat) Descriptor() protoreflect.EnumDescriptor {
	return file_pbschema_jwt_proto_enumTypes[1].Descriptor()
}

func (ResponseStatus_Stat) Type() protoreflect.EnumType {
	return &file_pbschema_jwt_proto_enumTypes[1]
}

func (x ResponseStatus_Stat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseStatus_Stat.Descriptor instead.
func (ResponseStatus_Stat) EnumDescriptor() ([]byte, []int) {
	return file_pbschema_jwt_proto_rawDescGZIP(), []int{3, 0}
}

type SignerMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Algo                     EncryptionAlgorithm `protobuf:"varint,1,opt,name=algo,proto3,enum=jwt.EncryptionAlgorithm" json:"algo,omitempty"`
	Iss                      string              `protobuf:"bytes,2,opt,name=iss,proto3" json:"iss,omitempty"`
	DefaultTTL               int64               `protobuf:"varint,3,opt,name=defaultTTL,proto3" json:"defaultTTL,omitempty"`                             //单位s
	DefaultEffectiveInterval int64               `protobuf:"varint,4,opt,name=defaultEffectiveInterval,proto3" json:"defaultEffectiveInterval,omitempty"` //单位s
	JtiGen                   string              `protobuf:"bytes,5,opt,name=jtiGen,proto3" json:"jtiGen,omitempty"`
}

func (x *SignerMeta) Reset() {
	*x = SignerMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbschema_jwt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignerMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignerMeta) ProtoMessage() {}

func (x *SignerMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pbschema_jwt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignerMeta.ProtoReflect.Descriptor instead.
func (*SignerMeta) Descriptor() ([]byte, []int) {
	return file_pbschema_jwt_proto_rawDescGZIP(), []int{0}
}

func (x *SignerMeta) GetAlgo() EncryptionAlgorithm {
	if x != nil {
		return x.Algo
	}
	return EncryptionAlgorithm_UNKNOWN
}

func (x *SignerMeta) GetIss() string {
	if x != nil {
		return x.Iss
	}
	return ""
}

func (x *SignerMeta) GetDefaultTTL() int64 {
	if x != nil {
		return x.DefaultTTL
	}
	return 0
}

func (x *SignerMeta) GetDefaultEffectiveInterval() int64 {
	if x != nil {
		return x.DefaultEffectiveInterval
	}
	return 0
}

func (x *SignerMeta) GetJtiGen() string {
	if x != nil {
		return x.JtiGen
	}
	return ""
}

type VerifierMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Algo            EncryptionAlgorithm `protobuf:"varint,1,opt,name=algo,proto3,enum=jwt.EncryptionAlgorithm" json:"algo,omitempty"`
	DefaultAUD      string              `protobuf:"bytes,2,opt,name=defaultAUD,proto3" json:"defaultAUD,omitempty"`
	DefaultISSRange []string            `protobuf:"bytes,3,rep,name=defaultISSRange,proto3" json:"defaultISSRange,omitempty"`
}

func (x *VerifierMeta) Reset() {
	*x = VerifierMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbschema_jwt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifierMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifierMeta) ProtoMessage() {}

func (x *VerifierMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pbschema_jwt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifierMeta.ProtoReflect.Descriptor instead.
func (*VerifierMeta) Descriptor() ([]byte, []int) {
	return file_pbschema_jwt_proto_rawDescGZIP(), []int{1}
}

func (x *VerifierMeta) GetAlgo() EncryptionAlgorithm {
	if x != nil {
		return x.Algo
	}
	return EncryptionAlgorithm_UNKNOWN
}

func (x *VerifierMeta) GetDefaultAUD() string {
	if x != nil {
		return x.DefaultAUD
	}
	return ""
}

func (x *VerifierMeta) GetDefaultISSRange() []string {
	if x != nil {
		return x.DefaultISSRange
	}
	return nil
}

type Token struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken  string `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	RefreshToken string `protobuf:"bytes,2,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
}

func (x *Token) Reset() {
	*x = Token{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbschema_jwt_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_pbschema_jwt_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_pbschema_jwt_proto_rawDescGZIP(), []int{2}
}

func (x *Token) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *Token) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type ResponseStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  ResponseStatus_Stat `protobuf:"varint,1,opt,name=status,proto3,enum=jwt.ResponseStatus_Stat" json:"status,omitempty"`
	Message string              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ResponseStatus) Reset() {
	*x = ResponseStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbschema_jwt_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseStatus) ProtoMessage() {}

func (x *ResponseStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pbschema_jwt_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseStatus.ProtoReflect.Descriptor instead.
func (*ResponseStatus) Descriptor() ([]byte, []int) {
	return file_pbschema_jwt_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseStatus) GetStatus() ResponseStatus_Stat {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_SUCCEED
}

func (x *ResponseStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pbschema_jwt_proto protoreflect.FileDescriptor

var file_pbschema_jwt_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x62, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x6a, 0x77, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6a, 0x77, 0x74, 0x22, 0xc0, 0x01, 0x0a, 0x0a, 0x53, 0x69,
	0x67, 0x6e, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x2c, 0x0a, 0x04, 0x61, 0x6c, 0x67, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6a, 0x77, 0x74, 0x2e, 0x45, 0x6e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d,
	0x52, 0x04, 0x61, 0x6c, 0x67, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x73, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x54, 0x54, 0x4c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x64, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x54, 0x54, 0x4c, 0x12, 0x3a, 0x0a, 0x18, 0x64, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x76, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x18, 0x64, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x76, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x6a, 0x74, 0x69, 0x47, 0x65, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6a, 0x74, 0x69, 0x47, 0x65, 0x6e, 0x22, 0x86, 0x01, 0x0a,
	0x0c, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x2c, 0x0a,
	0x04, 0x61, 0x6c, 0x67, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6a, 0x77,
	0x74, 0x2e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6c, 0x67, 0x6f,
	0x72, 0x69, 0x74, 0x68, 0x6d, 0x52, 0x04, 0x61, 0x6c, 0x67, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x64,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x41, 0x55, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x41, 0x55, 0x44, 0x12, 0x28, 0x0a, 0x0f, 0x64,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x49, 0x53, 0x53, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x49, 0x53, 0x53,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x22, 0x4d, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x20,
	0x0a, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x7d, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6a, 0x77, 0x74, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x1f, 0x0a, 0x04, 0x53, 0x74, 0x61, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55,
	0x43, 0x43, 0x45, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45,
	0x44, 0x10, 0x01, 0x2a, 0x85, 0x01, 0x0a, 0x13, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x12, 0x0b, 0x0a, 0x07, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x53, 0x32, 0x35,
	0x36, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x53, 0x33, 0x38, 0x34, 0x10, 0x02, 0x12, 0x09,
	0x0a, 0x05, 0x52, 0x53, 0x35, 0x31, 0x32, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x53, 0x32,
	0x35, 0x36, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x53, 0x33, 0x38, 0x34, 0x10, 0x05, 0x12,
	0x09, 0x0a, 0x05, 0x45, 0x53, 0x35, 0x31, 0x32, 0x10, 0x06, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x53,
	0x32, 0x35, 0x36, 0x10, 0x07, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x53, 0x33, 0x38, 0x34, 0x10, 0x08,
	0x12, 0x09, 0x0a, 0x05, 0x48, 0x53, 0x35, 0x31, 0x32, 0x10, 0x09, 0x42, 0x0a, 0x5a, 0x08, 0x2e,
	0x2f, 0x6a, 0x77, 0x74, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pbschema_jwt_proto_rawDescOnce sync.Once
	file_pbschema_jwt_proto_rawDescData = file_pbschema_jwt_proto_rawDesc
)

func file_pbschema_jwt_proto_rawDescGZIP() []byte {
	file_pbschema_jwt_proto_rawDescOnce.Do(func() {
		file_pbschema_jwt_proto_rawDescData = protoimpl.X.CompressGZIP(file_pbschema_jwt_proto_rawDescData)
	})
	return file_pbschema_jwt_proto_rawDescData
}

var file_pbschema_jwt_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pbschema_jwt_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pbschema_jwt_proto_goTypes = []interface{}{
	(EncryptionAlgorithm)(0), // 0: jwt.EncryptionAlgorithm
	(ResponseStatus_Stat)(0), // 1: jwt.ResponseStatus.Stat
	(*SignerMeta)(nil),       // 2: jwt.SignerMeta
	(*VerifierMeta)(nil),     // 3: jwt.VerifierMeta
	(*Token)(nil),            // 4: jwt.Token
	(*ResponseStatus)(nil),   // 5: jwt.ResponseStatus
}
var file_pbschema_jwt_proto_depIdxs = []int32{
	0, // 0: jwt.SignerMeta.algo:type_name -> jwt.EncryptionAlgorithm
	0, // 1: jwt.VerifierMeta.algo:type_name -> jwt.EncryptionAlgorithm
	1, // 2: jwt.ResponseStatus.status:type_name -> jwt.ResponseStatus.Stat
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pbschema_jwt_proto_init() }
func file_pbschema_jwt_proto_init() {
	if File_pbschema_jwt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pbschema_jwt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignerMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbschema_jwt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifierMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbschema_jwt_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Token); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbschema_jwt_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pbschema_jwt_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbschema_jwt_proto_goTypes,
		DependencyIndexes: file_pbschema_jwt_proto_depIdxs,
		EnumInfos:         file_pbschema_jwt_proto_enumTypes,
		MessageInfos:      file_pbschema_jwt_proto_msgTypes,
	}.Build()
	File_pbschema_jwt_proto = out.File
	file_pbschema_jwt_proto_rawDesc = nil
	file_pbschema_jwt_proto_goTypes = nil
	file_pbschema_jwt_proto_depIdxs = nil
}
