// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: protos/jwtsigner.proto

package signerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Jwtsigner_Meta_FullMethodName = "/jwt.signer.jwtsigner/Meta"
	Jwtsigner_Sign_FullMethodName = "/jwt.signer.jwtsigner/Sign"
)

// JwtsignerClient is the client API for Jwtsigner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JwtsignerClient interface {
	// 查看jwt服务元信息的算法
	Meta(ctx context.Context, in *MetaRequest, opts ...grpc.CallOption) (*MetaResponse, error)
	// Sign 为JSON字符串签名
	Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error)
}

type jwtsignerClient struct {
	cc grpc.ClientConnInterface
}

func NewJwtsignerClient(cc grpc.ClientConnInterface) JwtsignerClient {
	return &jwtsignerClient{cc}
}

func (c *jwtsignerClient) Meta(ctx context.Context, in *MetaRequest, opts ...grpc.CallOption) (*MetaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetaResponse)
	err := c.cc.Invoke(ctx, Jwtsigner_Meta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jwtsignerClient) Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignResponse)
	err := c.cc.Invoke(ctx, Jwtsigner_Sign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JwtsignerServer is the server API for Jwtsigner service.
// All implementations must embed UnimplementedJwtsignerServer
// for forward compatibility.
type JwtsignerServer interface {
	// 查看jwt服务元信息的算法
	Meta(context.Context, *MetaRequest) (*MetaResponse, error)
	// Sign 为JSON字符串签名
	Sign(context.Context, *SignRequest) (*SignResponse, error)
	mustEmbedUnimplementedJwtsignerServer()
}

// UnimplementedJwtsignerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJwtsignerServer struct{}

func (UnimplementedJwtsignerServer) Meta(context.Context, *MetaRequest) (*MetaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Meta not implemented")
}
func (UnimplementedJwtsignerServer) Sign(context.Context, *SignRequest) (*SignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Sign not implemented")
}
func (UnimplementedJwtsignerServer) mustEmbedUnimplementedJwtsignerServer() {}
func (UnimplementedJwtsignerServer) testEmbeddedByValue()                   {}

// UnsafeJwtsignerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JwtsignerServer will
// result in compilation errors.
type UnsafeJwtsignerServer interface {
	mustEmbedUnimplementedJwtsignerServer()
}

func RegisterJwtsignerServer(s grpc.ServiceRegistrar, srv JwtsignerServer) {
	// If the following call panics, it indicates UnimplementedJwtsignerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Jwtsigner_ServiceDesc, srv)
}

func _Jwtsigner_Meta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JwtsignerServer).Meta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Jwtsigner_Meta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JwtsignerServer).Meta(ctx, req.(*MetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Jwtsigner_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JwtsignerServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Jwtsigner_Sign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JwtsignerServer).Sign(ctx, req.(*SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Jwtsigner_ServiceDesc is the grpc.ServiceDesc for Jwtsigner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Jwtsigner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jwt.signer.jwtsigner",
	HandlerType: (*JwtsignerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Meta",
			Handler:    _Jwtsigner_Meta_Handler,
		},
		{
			MethodName: "Sign",
			Handler:    _Jwtsigner_Sign_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/jwtsigner.proto",
}
