// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: protos/jwtsigner.proto

package signerpb

import (
	jwtpb "github.com/Golang-Tools/jwthelper/contrib/pb/jwtpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaRequest) Reset() {
	*x = MetaRequest{}
	mi := &file_protos_jwtsigner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaRequest) ProtoMessage() {}

func (x *MetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_jwtsigner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaRequest.ProtoReflect.Descriptor instead.
func (*MetaRequest) Descriptor() ([]byte, []int) {
	return file_protos_jwtsigner_proto_rawDescGZIP(), []int{0}
}

type MetaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *jwtpb.ResponseStatus  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data          *jwtpb.SignerMeta      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaResponse) Reset() {
	*x = MetaResponse{}
	mi := &file_protos_jwtsigner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaResponse) ProtoMessage() {}

func (x *MetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_jwtsigner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaResponse.ProtoReflect.Descriptor instead.
func (*MetaResponse) Descriptor() ([]byte, []int) {
	return file_protos_jwtsigner_proto_rawDescGZIP(), []int{1}
}

func (x *MetaResponse) GetStatus() *jwtpb.ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *MetaResponse) GetData() *jwtpb.SignerMeta {
	if x != nil {
		return x.Data
	}
	return nil
}

type SignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sub           string                 `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`                //设置主题,一般用于放用户id
	Exp           int64                  `protobuf:"varint,2,opt,name=exp,proto3" json:"exp,omitempty"`               //超时时间,秒级时间戳
	Nbf           int64                  `protobuf:"varint,3,opt,name=nbf,proto3" json:"nbf,omitempty"`               //生效时间,秒级时间戳
	Refreshexp    int64                  `protobuf:"varint,4,opt,name=refreshexp,proto3" json:"refreshexp,omitempty"` //refresh_token的实效时间,秒级时间戳
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`        //其他负载,请以json格式传输
	Jti           string                 `protobuf:"bytes,6,opt,name=jti,proto3" json:"jti,omitempty"`                //设置token的id
	Aud           []string               `protobuf:"bytes,7,rep,name=aud,proto3" json:"aud,omitempty"`                //设置签名接收方,一般是app名或者url
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_protos_jwtsigner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_jwtsigner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_protos_jwtsigner_proto_rawDescGZIP(), []int{2}
}

func (x *SignRequest) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *SignRequest) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *SignRequest) GetNbf() int64 {
	if x != nil {
		return x.Nbf
	}
	return 0
}

func (x *SignRequest) GetRefreshexp() int64 {
	if x != nil {
		return x.Refreshexp
	}
	return 0
}

func (x *SignRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SignRequest) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

func (x *SignRequest) GetAud() []string {
	if x != nil {
		return x.Aud
	}
	return nil
}

type SignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *jwtpb.ResponseStatus  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Token         *jwtpb.Token           `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	mi := &file_protos_jwtsigner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_jwtsigner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_protos_jwtsigner_proto_rawDescGZIP(), []int{3}
}

func (x *SignResponse) GetStatus() *jwtpb.ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *SignResponse) GetToken() *jwtpb.Token {
	if x != nil {
		return x.Token
	}
	return nil
}

var File_protos_jwtsigner_proto protoreflect.FileDescriptor

const file_protos_jwtsigner_proto_rawDesc = "" +
	"\n" +
	"\x16protos/jwtsigner.proto\x12\n" +
	"jwt.signer\x1a\x10protos/jwt.proto\"\r\n" +
	"\vMetaRequest\"`\n" +
	"\fMetaResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x13.jwt.ResponseStatusR\x06status\x12#\n" +
	"\x04data\x18\x02 \x01(\v2\x0f.jwt.SignerMetaR\x04data\"\xa1\x01\n" +
	"\vSignRequest\x12\x10\n" +
	"\x03sub\x18\x01 \x01(\tR\x03sub\x12\x10\n" +
	"\x03exp\x18\x02 \x01(\x03R\x03exp\x12\x10\n" +
	"\x03nbf\x18\x03 \x01(\x03R\x03nbf\x12\x1e\n" +
	"\n" +
	"refreshexp\x18\x04 \x01(\x03R\n" +
	"refreshexp\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x10\n" +
	"\x03jti\x18\x06 \x01(\tR\x03jti\x12\x10\n" +
	"\x03aud\x18\a \x03(\tR\x03aud\"]\n" +
	"\fSignResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x13.jwt.ResponseStatusR\x06status\x12 \n" +
	"\x05token\x18\x02 \x01(\v2\n" +
	".jwt.TokenR\x05token2\x85\x01\n" +
	"\tjwtsigner\x12;\n" +
	"\x04Meta\x12\x17.jwt.signer.MetaRequest\x1a\x18.jwt.signer.MetaResponse\"\x00\x12;\n" +
	"\x04Sign\x12\x17.jwt.signer.SignRequest\x1a\x18.jwt.signer.SignResponse\"\x00B7Z5github.com/Golang-Tools/jwthelper/contrib/pb/signerpbb\x06proto3"

var (
	file_protos_jwtsigner_proto_rawDescOnce sync.Once
	file_protos_jwtsigner_proto_rawDescData []byte
)

func file_protos_jwtsigner_proto_rawDescGZIP() []byte {
	file_protos_jwtsigner_proto_rawDescOnce.Do(func() {
		file_protos_jwtsigner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_jwtsigner_proto_rawDesc), len(file_protos_jwtsigner_proto_rawDesc)))
	})
	return file_protos_jwtsigner_proto_rawDescData
}

var file_protos_jwtsigner_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_jwtsigner_proto_goTypes = []any{
	(*MetaRequest)(nil),          // 0: jwt.signer.MetaRequest
	(*MetaResponse)(nil),         // 1: jwt.signer.MetaResponse
	(*SignRequest)(nil),          // 2: jwt.signer.SignRequest
	(*SignResponse)(nil),         // 3: jwt.signer.SignResponse
	(*jwtpb.ResponseStatus)(nil), // 4: jwt.ResponseStatus
	(*jwtpb.SignerMeta)(nil),     // 5: jwt.SignerMeta
	(*jwtpb.Token)(nil),          // 6: jwt.Token
}
var file_protos_jwtsigner_proto_depIdxs = []int32{
	4, // 0: jwt.signer.MetaResponse.status:type_name -> jwt.ResponseStatus
	5, // 1: jwt.signer.MetaResponse.data:type_name -> jwt.SignerMeta
	4, // 2: jwt.signer.SignResponse.status:type_name -> jwt.ResponseStatus
	6, // 3: jwt.signer.SignResponse.token:type_name -> jwt.Token
	0, // 4: jwt.signer.jwtsigner.Meta:input_type -> jwt.signer.MetaRequest
	2, // 5: jwt.signer.jwtsigner.Sign:input_type -> jwt.signer.SignRequest
	1, // 6: jwt.signer.jwtsigner.Meta:output_type -> jwt.signer.MetaResponse
	3, // 7: jwt.signer.jwtsigner.Sign:output_type -> jwt.signer.SignResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protos_jwtsigner_proto_init() }
func file_protos_jwtsigner_proto_init() {
	if File_protos_jwtsigner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_jwtsigner_proto_rawDesc), len(file_protos_jwtsigner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_jwtsigner_proto_goTypes,
		DependencyIndexes: file_protos_jwtsigner_proto_depIdxs,
		MessageInfos:      file_protos_jwtsigner_proto_msgTypes,
	}.Build()
	File_protos_jwtsigner_proto = out.File
	file_protos_jwtsigner_proto_goTypes = nil
	file_protos_jwtsigner_proto_depIdxs = nil
}
