// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: protos/jwt.proto

package jwtpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncryptionAlgorithm int32

const (
	EncryptionAlgorithm_UNKNOWN EncryptionAlgorithm = 0
	EncryptionAlgorithm_HS256   EncryptionAlgorithm = 1
	EncryptionAlgorithm_HS384   EncryptionAlgorithm = 2
	EncryptionAlgorithm_HS512   EncryptionAlgorithm = 3
	EncryptionAlgorithm_RS256   EncryptionAlgorithm = 4
	EncryptionAlgorithm_RS384   EncryptionAlgorithm = 5
	EncryptionAlgorithm_RS512   EncryptionAlgorithm = 6
	EncryptionAlgorithm_ES256   EncryptionAlgorithm = 7
	EncryptionAlgorithm_ES384   EncryptionAlgorithm = 8
	EncryptionAlgorithm_ES512   EncryptionAlgorithm = 9
	EncryptionAlgorithm_EdDSA   EncryptionAlgorithm = 10
)

// Enum value maps for EncryptionAlgorithm.
var (
	EncryptionAlgorithm_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "HS256",
		2:  "HS384",
		3:  "HS512",
		4:  "RS256",
		5:  "RS384",
		6:  "RS512",
		7:  "ES256",
		8:  "ES384",
		9:  "ES512",
		10: "EdDSA",
	}
	EncryptionAlgorithm_value = map[string]int32{
		"UNKNOWN": 0,
		"HS256":   1,
		"HS384":   2,
		"HS512":   3,
		"RS256":   4,
		"RS384":   5,
		"RS512":   6,
		"ES256":   7,
		"ES384":   8,
		"ES512":   9,
		"EdDSA":   10,
	}
)

func (x EncryptionAlgorithm) Enum() *EncryptionAlgorithm {
	p := new(EncryptionAlgorithm)
	*p = x
	return p
}

func (x EncryptionAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EncryptionAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_jwt_proto_enumTypes[0].Descriptor()
}

func (EncryptionAlgorithm) Type() protoreflect.EnumType {
	return &file_protos_jwt_proto_enumTypes[0]
}

func (x EncryptionAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EncryptionAlgorithm.Descriptor instead.
func (EncryptionAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_protos_jwt_proto_rawDescGZIP(), []int{0}
}

type ResponseStatus_Stat int32

const (
	ResponseStatus_SUCCEED ResponseStatus_Stat = 0
	ResponseStatus_FAILED  ResponseStatus_Stat = 1
)

// Enum value maps for ResponseStatus_Stat.
var (
	ResponseStatus_Stat_name = map[int32]string{
		0: "SUCCEED",
		1: "FAILED",
	}
	ResponseStatus_Stat_value = map[string]int32{
		"SUCCEED": 0,
		"FAILED":  1,
	}
)

func (x ResponseStatus_Stat) Enum() *ResponseStatus_Stat {
	p := new(ResponseStatus_Stat)
	*p = x
	return p
}

func (x ResponseStatus_Stat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseStatus_Stat) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_jwt_proto_enumTypes[1].Descriptor()
}

func (ResponseStatus_Stat) Type() protoreflect.EnumType {
	return &file_protos_jwt_proto_enumTypes[1]
}

func (x ResponseStatus_Stat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseStatus_Stat.Descriptor instead.
func (ResponseStatus_Stat) EnumDescriptor() ([]byte, []int) {
	return file_protos_jwt_proto_rawDescGZIP(), []int{3, 0}
}

type SignerMeta struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Algo                     EncryptionAlgorithm    `protobuf:"varint,1,opt,name=algo,proto3,enum=jwt.EncryptionAlgorithm" json:"algo,omitempty"`
	Iss                      string                 `protobuf:"bytes,2,opt,name=iss,proto3" json:"iss,omitempty"`
	DefaultTTL               int64                  `protobuf:"varint,3,opt,name=defaultTTL,proto3" json:"defaultTTL,omitempty"`                             //单位s
	DefaultEffectiveInterval int64                  `protobuf:"varint,4,opt,name=defaultEffectiveInterval,proto3" json:"defaultEffectiveInterval,omitempty"` //单位s
	JtiGen                   string                 `protobuf:"bytes,5,opt,name=jtiGen,proto3" json:"jtiGen,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SignerMeta) Reset() {
	*x = SignerMeta{}
	mi := &file_protos_jwt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignerMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignerMeta) ProtoMessage() {}

func (x *SignerMeta) ProtoReflect() protoreflect.Message {
	mi := &file_protos_jwt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignerMeta.ProtoReflect.Descriptor instead.
func (*SignerMeta) Descriptor() ([]byte, []int) {
	return file_protos_jwt_proto_rawDescGZIP(), []int{0}
}

func (x *SignerMeta) GetAlgo() EncryptionAlgorithm {
	if x != nil {
		return x.Algo
	}
	return EncryptionAlgorithm_UNKNOWN
}

func (x *SignerMeta) GetIss() string {
	if x != nil {
		return x.Iss
	}
	return ""
}

func (x *SignerMeta) GetDefaultTTL() int64 {
	if x != nil {
		return x.DefaultTTL
	}
	return 0
}

func (x *SignerMeta) GetDefaultEffectiveInterval() int64 {
	if x != nil {
		return x.DefaultEffectiveInterval
	}
	return 0
}

func (x *SignerMeta) GetJtiGen() string {
	if x != nil {
		return x.JtiGen
	}
	return ""
}

type VerifierMeta struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Algo            EncryptionAlgorithm    `protobuf:"varint,1,opt,name=algo,proto3,enum=jwt.EncryptionAlgorithm" json:"algo,omitempty"`
	DefaultAUD      string                 `protobuf:"bytes,2,opt,name=defaultAUD,proto3" json:"defaultAUD,omitempty"`
	DefaultISSRange []string               `protobuf:"bytes,3,rep,name=defaultISSRange,proto3" json:"defaultISSRange,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VerifierMeta) Reset() {
	*x = VerifierMeta{}
	mi := &file_protos_jwt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifierMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifierMeta) ProtoMessage() {}

func (x *VerifierMeta) ProtoReflect() protoreflect.Message {
	mi := &file_protos_jwt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifierMeta.ProtoReflect.Descriptor instead.
func (*VerifierMeta) Descriptor() ([]byte, []int) {
	return file_protos_jwt_proto_rawDescGZIP(), []int{1}
}

func (x *VerifierMeta) GetAlgo() EncryptionAlgorithm {
	if x != nil {
		return x.Algo
	}
	return EncryptionAlgorithm_UNKNOWN
}

func (x *VerifierMeta) GetDefaultAUD() string {
	if x != nil {
		return x.DefaultAUD
	}
	return ""
}

func (x *VerifierMeta) GetDefaultISSRange() []string {
	if x != nil {
		return x.DefaultISSRange
	}
	return nil
}

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_protos_jwt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_protos_jwt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_protos_jwt_proto_rawDescGZIP(), []int{2}
}

func (x *Token) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *Token) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type ResponseStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ResponseStatus_Stat    `protobuf:"varint,1,opt,name=status,proto3,enum=jwt.ResponseStatus_Stat" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorKind     string                 `protobuf:"bytes,3,opt,name=error_kind,json=errorKind,proto3" json:"error_kind,omitempty"` //结构化错误分类名,取值见 exceptions.KindOf
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseStatus) Reset() {
	*x = ResponseStatus{}
	mi := &file_protos_jwt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseStatus) ProtoMessage() {}

func (x *ResponseStatus) ProtoReflect() protoreflect.Message {
	mi := &file_protos_jwt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseStatus.ProtoReflect.Descriptor instead.
func (*ResponseStatus) Descriptor() ([]byte, []int) {
	return file_protos_jwt_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseStatus) GetStatus() ResponseStatus_Stat {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_SUCCEED
}

func (x *ResponseStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseStatus) GetErrorKind() string {
	if x != nil {
		return x.ErrorKind
	}
	return ""
}

type JwtStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jti           string                 `protobuf:"bytes,1,opt,name=jti,proto3" json:"jti,omitempty"`
	Sub           string                 `protobuf:"bytes,2,opt,name=sub,proto3" json:"sub,omitempty"`
	Iss           string                 `protobuf:"bytes,3,opt,name=iss,proto3" json:"iss,omitempty"`
	TimeLeft      int64                  `protobuf:"varint,4,opt,name=time_left,json=timeLeft,proto3" json:"time_left,omitempty"`
	Aud           []string               `protobuf:"bytes,5,rep,name=aud,proto3" json:"aud,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwtStatus) Reset() {
	*x = JwtStatus{}
	mi := &file_protos_jwt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwtStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtStatus) ProtoMessage() {}

func (x *JwtStatus) ProtoReflect() protoreflect.Message {
	mi := &file_protos_jwt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtStatus.ProtoReflect.Descriptor instead.
func (*JwtStatus) Descriptor() ([]byte, []int) {
	return file_protos_jwt_proto_rawDescGZIP(), []int{4}
}

func (x *JwtStatus) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

func (x *JwtStatus) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *JwtStatus) GetIss() string {
	if x != nil {
		return x.Iss
	}
	return ""
}

func (x *JwtStatus) GetTimeLeft() int64 {
	if x != nil {
		return x.TimeLeft
	}
	return 0
}

func (x *JwtStatus) GetAud() []string {
	if x != nil {
		return x.Aud
	}
	return nil
}

var File_protos_jwt_proto protoreflect.FileDescriptor

const file_protos_jwt_proto_rawDesc = "" +
	"\n" +
	"\x10protos/jwt.proto\x12\x03jwt\"\xc0\x01\n" +
	"\n" +
	"SignerMeta\x12,\n" +
	"\x04algo\x18\x01 \x01(\x0e2\x18.jwt.EncryptionAlgorithmR\x04algo\x12\x10\n" +
	"\x03iss\x18\x02 \x01(\tR\x03iss\x12\x1e\n" +
	"\n" +
	"defaultTTL\x18\x03 \x01(\x03R\n" +
	"defaultTTL\x12:\n" +
	"\x18defaultEffectiveInterval\x18\x04 \x01(\x03R\x18defaultEffectiveInterval\x12\x16\n" +
	"\x06jtiGen\x18\x05 \x01(\tR\x06jtiGen\"\x86\x01\n" +
	"\fVerifierMeta\x12,\n" +
	"\x04algo\x18\x01 \x01(\x0e2\x18.jwt.EncryptionAlgorithmR\x04algo\x12\x1e\n" +
	"\n" +
	"defaultAUD\x18\x02 \x01(\tR\n" +
	"defaultAUD\x12(\n" +
	"\x0fdefaultISSRange\x18\x03 \x03(\tR\x0fdefaultISSRange\"M\n" +
	"\x05Token\x12 \n" +
	"\vAccessToken\x18\x01 \x01(\tR\vAccessToken\x12\"\n" +
	"\fRefreshToken\x18\x02 \x01(\tR\fRefreshToken\"\x9c\x01\n" +
	"\x0eResponseStatus\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.jwt.ResponseStatus.StatR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"error_kind\x18\x03 \x01(\tR\terrorKind\"\x1f\n" +
	"\x04Stat\x12\v\n" +
	"\aSUCCEED\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x01\"p\n" +
	"\tJwtStatus\x12\x10\n" +
	"\x03jti\x18\x01 \x01(\tR\x03jti\x12\x10\n" +
	"\x03sub\x18\x02 \x01(\tR\x03sub\x12\x10\n" +
	"\x03iss\x18\x03 \x01(\tR\x03iss\x12\x1b\n" +
	"\ttime_left\x18\x04 \x01(\x03R\btimeLeft\x12\x10\n" +
	"\x03aud\x18\x05 \x03(\tR\x03aud*\x90\x01\n" +
	"\x13EncryptionAlgorithm\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05HS256\x10\x01\x12\t\n" +
	"\x05HS384\x10\x02\x12\t\n" +
	"\x05HS512\x10\x03\x12\t\n" +
	"\x05RS256\x10\x04\x12\t\n" +
	"\x05RS384\x10\x05\x12\t\n" +
	"\x05RS512\x10\x06\x12\t\n" +
	"\x05ES256\x10\a\x12\t\n" +
	"\x05ES384\x10\b\x12\t\n" +
	"\x05ES512\x10\t\x12\t\n" +
	"\x05EdDSA\x10\n" +
	"B4Z2github.com/Golang-Tools/jwthelper/contrib/pb/jwtpbb\x06proto3"

var (
	file_protos_jwt_proto_rawDescOnce sync.Once
	file_protos_jwt_proto_rawDescData []byte
)

func file_protos_jwt_proto_rawDescGZIP() []byte {
	file_protos_jwt_proto_rawDescOnce.Do(func() {
		file_protos_jwt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_jwt_proto_rawDesc), len(file_protos_jwt_proto_rawDesc)))
	})
	return file_protos_jwt_proto_rawDescData
}

var file_protos_jwt_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protos_jwt_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protos_jwt_proto_goTypes = []any{
	(EncryptionAlgorithm)(0), // 0: jwt.EncryptionAlgorithm
	(ResponseStatus_Stat)(0), // 1: jwt.ResponseStatus.Stat
	(*SignerMeta)(nil),       // 2: jwt.SignerMeta
	(*VerifierMeta)(nil),     // 3: jwt.VerifierMeta
	(*Token)(nil),            // 4: jwt.Token
	(*ResponseStatus)(nil),   // 5: jwt.ResponseStatus
	(*JwtStatus)(nil),        // 6: jwt.JwtStatus
}
var file_protos_jwt_proto_depIdxs = []int32{
	0, // 0: jwt.SignerMeta.algo:type_name -> jwt.EncryptionAlgorithm
	0, // 1: jwt.VerifierMeta.algo:type_name -> jwt.EncryptionAlgorithm
	1, // 2: jwt.ResponseStatus.status:type_name -> jwt.ResponseStatus.Stat
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_jwt_proto_init() }
func file_protos_jwt_proto_init() {
	if File_protos_jwt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_jwt_proto_rawDesc), len(file_protos_jwt_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_jwt_proto_goTypes,
		DependencyIndexes: file_protos_jwt_proto_depIdxs,
		EnumInfos:         file_protos_jwt_proto_enumTypes,
		MessageInfos:      file_protos_jwt_proto_msgTypes,
	}.Build()
	File_protos_jwt_proto = out.File
	file_protos_jwt_proto_goTypes = nil
	file_protos_jwt_proto_depIdxs = nil
}
