// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: protos/jwtverifier.proto

package verifierpb

import (
	jwtpb "github.com/Golang-Tools/jwthelper/contrib/pb/jwtpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaRequest) Reset() {
	*x = MetaRequest{}
	mi := &file_protos_jwtverifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaRequest) ProtoMessage() {}

func (x *MetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_jwtverifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaRequest.ProtoReflect.Descriptor instead.
func (*MetaRequest) Descriptor() ([]byte, []int) {
	return file_protos_jwtverifier_proto_rawDescGZIP(), []int{0}
}

type MetaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *jwtpb.ResponseStatus  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data          *jwtpb.VerifierMeta    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaResponse) Reset() {
	*x = MetaResponse{}
	mi := &file_protos_jwtverifier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaResponse) ProtoMessage() {}

func (x *MetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_jwtverifier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaResponse.ProtoReflect.Descriptor instead.
func (*MetaResponse) Descriptor() ([]byte, []int) {
	return file_protos_jwtverifier_proto_rawDescGZIP(), []int{1}
}

func (x *MetaResponse) GetStatus() *jwtpb.ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *MetaResponse) GetData() *jwtpb.VerifierMeta {
	if x != nil {
		return x.Data
	}
	return nil
}

type VerifyRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Token                   *jwtpb.Token           `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                                                                           //要校验的token
	CheckMatchSub           string                 `protobuf:"bytes,2,opt,name=check_match_sub,json=checkMatchSub,proto3" json:"check_match_sub,omitempty"`                                    //校验sub是否符合这个字段填写的值
	CheckMatchallAud        []string               `protobuf:"bytes,3,rep,name=check_matchall_aud,json=checkMatchallAud,proto3" json:"check_matchall_aud,omitempty"`                           // 校验token的aud是不是包含这个字段中指定的值
	CheckMatchanyAud        []string               `protobuf:"bytes,4,rep,name=check_matchany_aud,json=checkMatchanyAud,proto3" json:"check_matchany_aud,omitempty"`                           // 校验token的aud是不是包含这个字段中指定的值
	CheckNotmatchAud        []string               `protobuf:"bytes,5,rep,name=check_notmatch_aud,json=checkNotmatchAud,proto3" json:"check_notmatch_aud,omitempty"`                           // 校验token的aud是不是包含这个字段中指定的值
	CheckMatchIss           []string               `protobuf:"bytes,6,rep,name=check_match_iss,json=checkMatchIss,proto3" json:"check_match_iss,omitempty"`                                    //校验token的签发人是否在这个字段给定的范围中
	NotCheckRefreshTokenAud bool                   `protobuf:"varint,7,opt,name=not_check_refresh_token_aud,json=notCheckRefreshTokenAud,proto3" json:"not_check_refresh_token_aud,omitempty"` //是否校验RefreshToken中的AUD必须和对应AccessToken的一致
	NotCheckRefreshTokenJti bool                   `protobuf:"varint,8,opt,name=not_check_refresh_token_jti,json=notCheckRefreshTokenJti,proto3" json:"not_check_refresh_token_jti,omitempty"` //是否校验RefreshToken中的JTI必须和对应AccessToken的一致
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_protos_jwtverifier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_jwtverifier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_protos_jwtverifier_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyRequest) GetToken() *jwtpb.Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *VerifyRequest) GetCheckMatchSub() string {
	if x != nil {
		return x.CheckMatchSub
	}
	return ""
}

func (x *VerifyRequest) GetCheckMatchallAud() []string {
	if x != nil {
		return x.CheckMatchallAud
	}
	return nil
}

func (x *VerifyRequest) GetCheckMatchanyAud() []string {
	if x != nil {
		return x.CheckMatchanyAud
	}
	return nil
}

func (x *VerifyRequest) GetCheckNotmatchAud() []string {
	if x != nil {
		return x.CheckNotmatchAud
	}
	return nil
}

func (x *VerifyRequest) GetCheckMatchIss() []string {
	if x != nil {
		return x.CheckMatchIss
	}
	return nil
}

func (x *VerifyRequest) GetNotCheckRefreshTokenAud() bool {
	if x != nil {
		return x.NotCheckRefreshTokenAud
	}
	return false
}

func (x *VerifyRequest) GetNotCheckRefreshTokenJti() bool {
	if x != nil {
		return x.NotCheckRefreshTokenJti
	}
	return false
}

type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *jwtpb.ResponseStatus  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	JwtStatus     *jwtpb.JwtStatus       `protobuf:"bytes,2,opt,name=jwt_status,json=jwtStatus,proto3" json:"jwt_status,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_protos_jwtverifier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_jwtverifier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_protos_jwtverifier_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyResponse) GetStatus() *jwtpb.ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *VerifyResponse) GetJwtStatus() *jwtpb.JwtStatus {
	if x != nil {
		return x.JwtStatus
	}
	return nil
}

func (x *VerifyResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_protos_jwtverifier_proto protoreflect.FileDescriptor

const file_protos_jwtverifier_proto_rawDesc = "" +
	"\n" +
	"\x18protos/jwtverifier.proto\x12\fjwt.verifier\x1a\x10protos/jwt.proto\"\r\n" +
	"\vMetaRequest\"b\n" +
	"\fMetaResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x13.jwt.ResponseStatusR\x06status\x12%\n" +
	"\x04data\x18\x02 \x01(\v2\x11.jwt.VerifierMetaR\x04data\"\x87\x03\n" +
	"\rVerifyRequest\x12 \n" +
	"\x05token\x18\x01 \x01(\v2\n" +
	".jwt.TokenR\x05token\x12&\n" +
	"\x0fcheck_match_sub\x18\x02 \x01(\tR\rcheckMatchSub\x12,\n" +
	"\x12check_matchall_aud\x18\x03 \x03(\tR\x10checkMatchallAud\x12,\n" +
	"\x12check_matchany_aud\x18\x04 \x03(\tR\x10checkMatchanyAud\x12,\n" +
	"\x12check_notmatch_aud\x18\x05 \x03(\tR\x10checkNotmatchAud\x12&\n" +
	"\x0fcheck_match_iss\x18\x06 \x03(\tR\rcheckMatchIss\x12<\n" +
	"\x1bnot_check_refresh_token_aud\x18\a \x01(\bR\x17notCheckRefreshTokenAud\x12<\n" +
	"\x1bnot_check_refresh_token_jti\x18\b \x01(\bR\x17notCheckRefreshTokenJti\"\x86\x01\n" +
	"\x0eVerifyResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x13.jwt.ResponseStatusR\x06status\x12-\n" +
	"\n" +
	"jwt_status\x18\x02 \x01(\v2\x0e.jwt.JwtStatusR\tjwtStatus\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload2\x95\x01\n" +
	"\vjwtverifier\x12?\n" +
	"\x04Meta\x12\x19.jwt.verifier.MetaRequest\x1a\x1a.jwt.verifier.MetaResponse\"\x00\x12E\n" +
	"\x06Verify\x12\x1b.jwt.verifier.VerifyRequest\x1a\x1c.jwt.verifier.VerifyResponse\"\x00B9Z7github.com/Golang-Tools/jwthelper/contrib/pb/verifierpbb\x06proto3"

var (
	file_protos_jwtverifier_proto_rawDescOnce sync.Once
	file_protos_jwtverifier_proto_rawDescData []byte
)

func file_protos_jwtverifier_proto_rawDescGZIP() []byte {
	file_protos_jwtverifier_proto_rawDescOnce.Do(func() {
		file_protos_jwtverifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_jwtverifier_proto_rawDesc), len(file_protos_jwtverifier_proto_rawDesc)))
	})
	return file_protos_jwtverifier_proto_rawDescData
}

var file_protos_jwtverifier_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_jwtverifier_proto_goTypes = []any{
	(*MetaRequest)(nil),          // 0: jwt.verifier.MetaRequest
	(*MetaResponse)(nil),         // 1: jwt.verifier.MetaResponse
	(*VerifyRequest)(nil),        // 2: jwt.verifier.VerifyRequest
	(*VerifyResponse)(nil),       // 3: jwt.verifier.VerifyResponse
	(*jwtpb.ResponseStatus)(nil), // 4: jwt.ResponseStatus
	(*jwtpb.VerifierMeta)(nil),   // 5: jwt.VerifierMeta
	(*jwtpb.Token)(nil),          // 6: jwt.Token
	(*jwtpb.JwtStatus)(nil),      // 7: jwt.JwtStatus
}
var file_protos_jwtverifier_proto_depIdxs = []int32{
	4, // 0: jwt.verifier.MetaResponse.status:type_name -> jwt.ResponseStatus
	5, // 1: jwt.verifier.MetaResponse.data:type_name -> jwt.VerifierMeta
	6, // 2: jwt.verifier.VerifyRequest.token:type_name -> jwt.Token
	4, // 3: jwt.verifier.VerifyResponse.status:type_name -> jwt.ResponseStatus
	7, // 4: jwt.verifier.VerifyResponse.jwt_status:type_name -> jwt.JwtStatus
	0, // 5: jwt.verifier.jwtverifier.Meta:input_type -> jwt.verifier.MetaRequest
	2, // 6: jwt.verifier.jwtverifier.Verify:input_type -> jwt.verifier.VerifyRequest
	1, // 7: jwt.verifier.jwtverifier.Meta:output_type -> jwt.verifier.MetaResponse
	3, // 8: jwt.verifier.jwtverifier.Verify:output_type -> jwt.verifier.VerifyResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_protos_jwtverifier_proto_init() }
func file_protos_jwtverifier_proto_init() {
	if File_protos_jwtverifier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_jwtverifier_proto_rawDesc), len(file_protos_jwtverifier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_jwtverifier_proto_goTypes,
		DependencyIndexes: file_protos_jwtverifier_proto_depIdxs,
		MessageInfos:      file_protos_jwtverifier_proto_msgTypes,
	}.Build()
	File_protos_jwtverifier_proto = out.File
	file_protos_jwtverifier_proto_goTypes = nil
	file_protos_jwtverifier_proto_depIdxs = nil
}
