// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.1
// source: pbschema/jwtverifier.proto

package jwtverifier_pb

import (
	jwt_pb "github.com/Golang-Tools/jwthelper/jwt_pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MetaRequest) Reset() {
	*x = MetaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbschema_jwtverifier_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaRequest) ProtoMessage() {}

func (x *MetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pbschema_jwtverifier_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaRequest.ProtoReflect.Descriptor instead.
func (*MetaRequest) Descriptor() ([]byte, []int) {
	return file_pbschema_jwtverifier_proto_rawDescGZIP(), []int{0}
}

type MetaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *jwt_pb.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data   *jwt_pb.VerifierMeta   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *MetaResponse) Reset() {
	*x = MetaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbschema_jwtverifier_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaResponse) ProtoMessage() {}

func (x *MetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pbschema_jwtverifier_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaResponse.ProtoReflect.Descriptor instead.
func (*MetaResponse) Descriptor() ([]byte, []int) {
	return file_pbschema_jwtverifier_proto_rawDescGZIP(), []int{1}
}

func (x *MetaResponse) GetStatus() *jwt_pb.ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *MetaResponse) GetData() *jwt_pb.VerifierMeta {
	if x != nil {
		return x.Data
	}
	return nil
}

type VerifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token                   *jwt_pb.Token `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                                                                           //要校验的token
	CheckMatchSub           string        `protobuf:"bytes,2,opt,name=check_match_sub,json=checkMatchSub,proto3" json:"check_match_sub,omitempty"`                                    //校验sub是否符合这个字段填写的值
	CheckMatchAud           string        `protobuf:"bytes,3,opt,name=check_match_aud,json=checkMatchAud,proto3" json:"check_match_aud,omitempty"`                                    // 校验token的aud是不是包含这个字段中指定的值
	CheckMatchIss           []string      `protobuf:"bytes,4,rep,name=check_match_iss,json=checkMatchIss,proto3" json:"check_match_iss,omitempty"`                                    //校验token的签发人是否在这个字段给定的范围中
	NotCheckRefreshTokenAud bool          `protobuf:"varint,5,opt,name=not_check_refresh_token_aud,json=notCheckRefreshTokenAud,proto3" json:"not_check_refresh_token_aud,omitempty"` //是否校验RefreshToken中的AUD必须和对应AccessToken的一致
	NotCheckRefreshTokenJti bool          `protobuf:"varint,6,opt,name=not_check_refresh_token_jti,json=notCheckRefreshTokenJti,proto3" json:"not_check_refresh_token_jti,omitempty"` //是否校验RefreshToken中的JTI必须和对应AccessToken的一致
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbschema_jwtverifier_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pbschema_jwtverifier_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_pbschema_jwtverifier_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyRequest) GetToken() *jwt_pb.Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *VerifyRequest) GetCheckMatchSub() string {
	if x != nil {
		return x.CheckMatchSub
	}
	return ""
}

func (x *VerifyRequest) GetCheckMatchAud() string {
	if x != nil {
		return x.CheckMatchAud
	}
	return ""
}

func (x *VerifyRequest) GetCheckMatchIss() []string {
	if x != nil {
		return x.CheckMatchIss
	}
	return nil
}

func (x *VerifyRequest) GetNotCheckRefreshTokenAud() bool {
	if x != nil {
		return x.NotCheckRefreshTokenAud
	}
	return false
}

func (x *VerifyRequest) GetNotCheckRefreshTokenJti() bool {
	if x != nil {
		return x.NotCheckRefreshTokenJti
	}
	return false
}

type VerifyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    *jwt_pb.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	JwtStatus *jwt_pb.JwtStatus      `protobuf:"bytes,2,opt,name=jwt_status,json=jwtStatus,proto3" json:"jwt_status,omitempty"`
	Payload   []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbschema_jwtverifier_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pbschema_jwtverifier_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_pbschema_jwtverifier_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyResponse) GetStatus() *jwt_pb.ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *VerifyResponse) GetJwtStatus() *jwt_pb.JwtStatus {
	if x != nil {
		return x.JwtStatus
	}
	return nil
}

func (x *VerifyResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_pbschema_jwtverifier_proto protoreflect.FileDescriptor

var file_pbschema_jwtverifier_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x62, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x6a, 0x77, 0x74, 0x76, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6a, 0x77,
	0x74, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x1a, 0x12, 0x70, 0x62, 0x73, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x2f, 0x6a, 0x77, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0d,
	0x0a, 0x0b, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x62, 0x0a,
	0x0c, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x6a, 0x77, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6a, 0x77, 0x74, 0x2e, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0xa5, 0x02, 0x0a, 0x0d, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6a, 0x77, 0x74, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x26, 0x0a, 0x0f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x75, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x75, 0x62, 0x12, 0x26, 0x0a,
	0x0f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x61, 0x75, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x41, 0x75, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x73, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x73, 0x73, 0x12, 0x3c, 0x0a,
	0x1b, 0x6e, 0x6f, 0x74, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x72, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x61, 0x75, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x17, 0x6e, 0x6f, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x66, 0x72,
	0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x75, 0x64, 0x12, 0x3c, 0x0a, 0x1b, 0x6e,
	0x6f, 0x74, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6a, 0x74, 0x69, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x17, 0x6e, 0x6f, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4a, 0x74, 0x69, 0x22, 0x86, 0x01, 0x0a, 0x0e, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6a,
	0x77, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2d, 0x0a, 0x0a, 0x6a, 0x77, 0x74,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x6a, 0x77, 0x74, 0x2e, 0x4a, 0x77, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x09, 0x6a,
	0x77, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x32, 0x95, 0x01, 0x0a, 0x0b, 0x6a, 0x77, 0x74, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x12, 0x3f, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x19, 0x2e, 0x6a, 0x77, 0x74,
	0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6a, 0x77, 0x74, 0x2e, 0x76, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x06, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x1b, 0x2e,
	0x6a, 0x77, 0x74, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6a, 0x77, 0x74,
	0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f,
	0x6a, 0x77, 0x74, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x5f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pbschema_jwtverifier_proto_rawDescOnce sync.Once
	file_pbschema_jwtverifier_proto_rawDescData = file_pbschema_jwtverifier_proto_rawDesc
)

func file_pbschema_jwtverifier_proto_rawDescGZIP() []byte {
	file_pbschema_jwtverifier_proto_rawDescOnce.Do(func() {
		file_pbschema_jwtverifier_proto_rawDescData = protoimpl.X.CompressGZIP(file_pbschema_jwtverifier_proto_rawDescData)
	})
	return file_pbschema_jwtverifier_proto_rawDescData
}

var file_pbschema_jwtverifier_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pbschema_jwtverifier_proto_goTypes = []interface{}{
	(*MetaRequest)(nil),           // 0: jwt.verifier.MetaRequest
	(*MetaResponse)(nil),          // 1: jwt.verifier.MetaResponse
	(*VerifyRequest)(nil),         // 2: jwt.verifier.VerifyRequest
	(*VerifyResponse)(nil),        // 3: jwt.verifier.VerifyResponse
	(*jwt_pb.ResponseStatus)(nil), // 4: jwt.ResponseStatus
	(*jwt_pb.VerifierMeta)(nil),   // 5: jwt.VerifierMeta
	(*jwt_pb.Token)(nil),          // 6: jwt.Token
	(*jwt_pb.JwtStatus)(nil),      // 7: jwt.JwtStatus
}
var file_pbschema_jwtverifier_proto_depIdxs = []int32{
	4, // 0: jwt.verifier.MetaResponse.status:type_name -> jwt.ResponseStatus
	5, // 1: jwt.verifier.MetaResponse.data:type_name -> jwt.VerifierMeta
	6, // 2: jwt.verifier.VerifyRequest.token:type_name -> jwt.Token
	4, // 3: jwt.verifier.VerifyResponse.status:type_name -> jwt.ResponseStatus
	7, // 4: jwt.verifier.VerifyResponse.jwt_status:type_name -> jwt.JwtStatus
	0, // 5: jwt.verifier.jwtverifier.Meta:input_type -> jwt.verifier.MetaRequest
	2, // 6: jwt.verifier.jwtverifier.Verify:input_type -> jwt.verifier.VerifyRequest
	1, // 7: jwt.verifier.jwtverifier.Meta:output_type -> jwt.verifier.MetaResponse
	3, // 8: jwt.verifier.jwtverifier.Verify:output_type -> jwt.verifier.VerifyResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pbschema_jwtverifier_proto_init() }
func file_pbschema_jwtverifier_proto_init() {
	if File_pbschema_jwtverifier_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pbschema_jwtverifier_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbschema_jwtverifier_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbschema_jwtverifier_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbschema_jwtverifier_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pbschema_jwtverifier_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pbschema_jwtverifier_proto_goTypes,
		DependencyIndexes: file_pbschema_jwtverifier_proto_depIdxs,
		MessageInfos:      file_pbschema_jwtverifier_proto_msgTypes,
	}.Build()
	File_pbschema_jwtverifier_proto = out.File
	file_pbschema_jwtverifier_proto_rawDesc = nil
	file_pbschema_jwtverifier_proto_goTypes = nil
	file_pbschema_jwtverifier_proto_depIdxs = nil
}
